// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// clogitl1_c
NumericMatrix clogitl1_c(NumericVector n, NumericVector m, NumericMatrix Xmat, NumericVector yvec, int switchIter, int numLambda, double minLambda, double alpha);
RcppExport SEXP clogitL1_clogitl1_c(SEXP nSEXP, SEXP mSEXP, SEXP XmatSEXP, SEXP yvecSEXP, SEXP switchIterSEXP, SEXP numLambdaSEXP, SEXP minLambdaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    NumericVector n = Rcpp::as<NumericVector >(nSEXP);
    NumericVector m = Rcpp::as<NumericVector >(mSEXP);
    NumericMatrix Xmat = Rcpp::as<NumericMatrix >(XmatSEXP);
    NumericVector yvec = Rcpp::as<NumericVector >(yvecSEXP);
    int switchIter = Rcpp::as<int >(switchIterSEXP);
    int numLambda = Rcpp::as<int >(numLambdaSEXP);
    double minLambda = Rcpp::as<double >(minLambdaSEXP);
    double alpha = Rcpp::as<double >(alphaSEXP);
    NumericMatrix __result = clogitl1_c(n, m, Xmat, yvec, switchIter, numLambda, minLambda, alpha);
    return Rcpp::wrap(__result);
END_RCPP
}
// clogitl1CV_c
NumericMatrix clogitl1CV_c(NumericVector n, NumericVector m, NumericMatrix Xmat, NumericVector yvec, NumericVector lambdas, NumericVector keepvec, double alpha);
RcppExport SEXP clogitL1_clogitl1CV_c(SEXP nSEXP, SEXP mSEXP, SEXP XmatSEXP, SEXP yvecSEXP, SEXP lambdasSEXP, SEXP keepvecSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    NumericVector n = Rcpp::as<NumericVector >(nSEXP);
    NumericVector m = Rcpp::as<NumericVector >(mSEXP);
    NumericMatrix Xmat = Rcpp::as<NumericMatrix >(XmatSEXP);
    NumericVector yvec = Rcpp::as<NumericVector >(yvecSEXP);
    NumericVector lambdas = Rcpp::as<NumericVector >(lambdasSEXP);
    NumericVector keepvec = Rcpp::as<NumericVector >(keepvecSEXP);
    double alpha = Rcpp::as<double >(alphaSEXP);
    NumericMatrix __result = clogitl1CV_c(n, m, Xmat, yvec, lambdas, keepvec, alpha);
    return Rcpp::wrap(__result);
END_RCPP
}
